# Generated by Django 4.0 on 2022-01-29 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medical_entries',
            old_name='descripton',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='medical_entries',
            old_name='job_id',
            new_name='med_id',
        ),
    ]
